### ISSUE TITLE
As a user or visitor  I want to visit home page, so that I can check out recBooker

### ISSUE THREAD

**Issue by johnlobster** [johnlobster/recBooker#22]
#### User

Anyone on internet

#### Task

Create home page

#### Goal

* Information about recBooker
* links to login and registration pages
* link to facility view page

### Sub tasks

- [ ] populate main.handlebars with relevant <head> elements
- [ ] Add a banner/jumbotron to main.handlebars
- [ ] Add html to index.handlebars
- [ ] links to /register /login /facilities
