### ISSUE TITLE
As a registered user I want to login, so that I can make and view facility bookings

### ISSUE THREAD

**Issue by johnlobster** [johnlobster/recBooker#23]
#### User

Registered : user name is in database

#### Task

Log in - front end and back end knows who the user is
#### Goal

Access all user features of recBooker

### Sub tasks

- [ ] Create login.handlebars 
- [ ] login page to POST a form to /api/login with body containing JSON object {name:, password:}. 
- [ ] html route for /login
- [ ] api route for /api/login . Returns request object if login is successful. Empty body if not successful
- [ ] test

**Comment by Sidetrack-CA** [comment]
I have added the /api/login route which checks to see if a user exists in the DB and if so it returns the user information as a JSON object.  If the user does not exist it returns null.
